#!/bin/bash
cat $2 >> ~/codes/allcommits.log && git commit -m "$1" && cat $1 >> ~/codes/allcommits.log && git branch | grep \* | cut -d ' ' -f2 >> ~/codes/allcommits.log && git remote show origin >> ~/codes/allcommits.log && echo "" >> ~/codes/allcommits.log
